Decimal score = math.random()*100;
Integer studentScore = Integer.valueOf(score);
System.debug(StudentScore);
if (StudentScore >=90){
    System.debug('A');
} else if (StudentScore >=80){
    System.debug('B');
} else if (StudentScore >=70){
    System.debug('C');
} else if (StudentScore >=60){
    System.debug('D');
} else if (StudentScore >=50){
    System.debug('E');
} else { System.debug('F');
}